### ISSUE TITLE
Needed optimization and correction of few bugs

### ISSUE THREAD

**Issue by aneri0x4f** [sameepv21/Resource_Management_System#1]
1. You have used fetch to get response from the backend. There is a better third-party-package "axios" that can be used instead.
Axios can save the extra step of parsing the response from the backend, hence optimizing the code when there are large number of responses required (and you need not parse them to JSON object).
2. You could use cookie along with session so you need not send request to backend for "already loggedin status". Instead the data would be stored in the frontend using cookie.

**Comment by sameepv21** [comment]
1. Yes, thank you for your suggestion. I have already started to change my code and used axios at some places. The problem I faced with axios was that, with fetch, my session was stored, whereas with axios my session is not being stored even though I have not changed the code where I have implemented session.

2. Oh! I think this is the problem with using axios, I must use cookies. Thank you so much for the suggestion. Could you help modifying the code?

**Comment by aneri0x4f** [comment]
Good to know.
Sure I can create a pull request for the edited code by noon : )

**Comment by sameepv21** [comment]
Thank you so much.

**Comment by sameepv21** [comment]
Thank you, I have merged your pull request.

**Comment by sameepv21** [comment]
I reviewed your code, can you please also help me by perfectly implementing sessions and cookies?

**Comment by aneri0x4f** [comment]
Yes sure :)

**Comment by sameepv21** [comment]
Thank you for your help :)
